ALTER TABLE boards ADD COLUMN status TEXT NOT NULL DEFAULT 'published';
ALTER TABLE classes ADD COLUMN status TEXT NOT NULL DEFAULT 'published';
ALTER TABLE streams ADD COLUMN status TEXT NOT NULL DEFAULT 'published';