# infra/azure/ai-services.tf
#
# Phase 5b — Azure-native advanced features (Task #338).
#
# Provisions the ten Azure-native AI services that light up alongside
# the cron + observability landing zone (Task #329) and the cron port
# (Task #332). Each service is registered as an *additional* path in
# the existing AI Gateway / OCR / TTS / moderation / search /
# personalisation chains — never as a replacement. See
# `docs/features/azure-native.md` for the runtime wiring and admin
# toggles.
#
# Hosting-plan invariants (carried over from
# `docs/infra/cloud-allocation-plan.md`):
#
#   • Azure Blob Storage is NOT used. Any artefact persistence
#     (Custom Neural Voice training corpora, AI Search blob ingest)
#     points at S3 via the existing AWS-side bucket; on the Azure
#     side those services reach S3 over their public endpoint with
#     a presigned URL the cron job mints. There is no
#     `azurerm_storage_account` in this file by design.
#
#   • Azure OpenAI handles GPT-4.1-mini chat/content roles, NOT
#     Bedrock (Bedrock is Cohere-only on the AWS side).
#
#   • The cron-tier runtime managed identity
#     (`azurerm_user_assigned_identity.cron_jobs_runtime`) is the
#     single principal that all Azure AI services authenticate as
#     from the backend / cron jobs. No static keys are minted; each
#     service receives a scoped `Cognitive Services User` (or
#     equivalent) role assignment plus its endpoint URL written to
#     Key Vault as a non-sensitive reference.
#
#   • The endpoint URLs are written to Key Vault (not as env vars)
#     so rotation flows match the existing Phase 1c secret model.
#     No API keys are written — managed identity bearer tokens are
#     fetched at call time.

# ─── Shared locals ──────────────────────────────────────────────────────────

locals {
  # Suffix keeps every Azure AI account globally unique without
  # leaking the subscription ID into resource names.
  ai_name_suffix = substr(sha1(data.azurerm_subscription.current.id), 0, 6)

  # Per-feature SKU + region map. Most Cognitive Services SKUs are
  # `S0` (standard pay-as-you-go); Personalizer + Anomaly Detector
  # have their own tiers. Region pinning matches data-residency
  # constraints (Indic content stays in `centralindia` where the
  # service supports it; falls back to `eastus` for services that
  # are not yet GA in `centralindia`).
  ai_services = {
    openai              = { sku = "S0", region = "eastus",       kind = "OpenAI",          purpose = "Additional LLM target wired into AI Gateway routing" }
    speech              = { sku = "S0", region = "centralindia", kind = "SpeechServices",  purpose = "Indic STT/TTS fallback + Custom Neural Voice 'Syra'" }
    translator          = { sku = "S1", region = "global",       kind = "TextTranslation", purpose = "Indic <-> English translation fallback (Sarvam parallel)" }
    document_intel      = { sku = "S0", region = "centralindia", kind = "FormRecognizer",  purpose = "Layout-aware OCR for past papers / marks sheets" }
    vision              = { sku = "S1", region = "centralindia", kind = "ComputerVision",  purpose = "OCR + image-understanding fallback tier" }
    content_safety      = { sku = "S0", region = "eastus",       kind = "ContentSafety",   purpose = "Sync moderation on chat I/O + uploads" }
    language            = { sku = "S",  region = "centralindia", kind = "TextAnalytics",   purpose = "Key phrases + entities + summaries + PII detection" }
    anomaly_detector    = { sku = "S0", region = "eastus",       kind = "AnomalyDetector", purpose = "Credit-burn / error-rate / R2-cost anomaly alerts" }
    personalizer        = { sku = "S0", region = "westeurope",   kind = "Personalizer",    purpose = "Next-best-quiz A/B vs deterministic ranker" }
  }
}

# ─── Cognitive Services accounts (9 of 10 services) ─────────────────────────
# AI Search is provisioned separately via `azurerm_search_service`
# (Cognitive Services does not cover it).

resource "azurerm_cognitive_account" "ai" {
  for_each = local.ai_services

  name                  = "${local.lz_project}-ai-${each.key}-${local.ai_name_suffix}"
  resource_group_name   = azurerm_resource_group.cron_obs.name
  location              = each.value.region
  kind                  = each.value.kind
  sku_name              = each.value.sku
  custom_subdomain_name = "${local.lz_project}-${each.key}-${local.ai_name_suffix}"

  # Managed-identity-only auth. The local key is still generated by
  # the platform but the runtime never reads it — `local_auth_enabled
  # = false` blocks API-key auth at the data plane so a leaked key
  # cannot be used.
  local_auth_enabled            = false
  public_network_access_enabled = true

  identity {
    type = "SystemAssigned"
  }

  # Every account inherits the landing-zone tag set plus a
  # per-feature tag so cost reports group cleanly by AI surface.
  tags = merge(local.lz_common_tags, {
    "ai-feature" = each.key
    "ai-purpose" = each.value.purpose
  })
}

# Cron-jobs runtime identity gets `Cognitive Services User` on every
# account — enough to call the data plane, NOT to rotate keys, change
# pricing tier, or read diagnostic settings.
resource "azurerm_role_assignment" "cron_runtime_ai_user" {
  for_each = local.ai_services

  scope                = azurerm_cognitive_account.ai[each.key].id
  role_definition_name = "Cognitive Services User"
  principal_id         = azurerm_user_assigned_identity.cron_jobs_runtime.principal_id
}

# Endpoint URLs are written to Key Vault as non-sensitive references
# so Python wrappers in `services/backend/azure_ai/` resolve them via
# the same code path used by every other Azure-side secret. The
# secret VALUE is the endpoint URL (public information); the API key
# is intentionally NEVER written to Key Vault.
resource "azurerm_key_vault_secret" "ai_endpoint" {
  for_each = local.ai_services

  name         = "azure-ai-${each.key}-endpoint"
  value        = azurerm_cognitive_account.ai[each.key].endpoint
  key_vault_id = azurerm_key_vault.cron_obs.id
  content_type = "text/url"

  tags = {
    "ai-feature" = each.key
    "secret-kind" = "endpoint-url"
  }

  depends_on = [azurerm_role_assignment.kv_secrets_officer_terraform_runner]
}

# ─── Azure AI Search (separate resource type) ───────────────────────────────

resource "azurerm_search_service" "library" {
  name                = "${local.lz_project}-ai-search-${local.ai_name_suffix}"
  resource_group_name = azurerm_resource_group.cron_obs.name
  location            = local.lz_primary_region
  sku                 = "basic" # 2 GB index ceiling — fits the library snapshot with headroom; bump to `standard` if/when impressions force a vector-index split.
  replica_count       = 1
  partition_count     = 1

  local_authentication_enabled = false # MI-only, mirrors Cognitive Services
  authentication_failure_mode  = "http403"

  identity {
    type = "SystemAssigned"
  }

  tags = merge(local.lz_common_tags, {
    "ai-feature" = "search"
    "ai-purpose" = "Hybrid retriever A/B vs Pinecone for RAG"
  })
}

# Cron + backend identity gets data-plane read/write so the indexer
# job can push library snapshots and the RAG path can query.
resource "azurerm_role_assignment" "cron_runtime_search_contributor" {
  scope                = azurerm_search_service.library.id
  role_definition_name = "Search Index Data Contributor"
  principal_id         = azurerm_user_assigned_identity.cron_jobs_runtime.principal_id
}

resource "azurerm_role_assignment" "cron_runtime_search_reader" {
  scope                = azurerm_search_service.library.id
  role_definition_name = "Search Index Data Reader"
  principal_id         = azurerm_user_assigned_identity.cron_jobs_runtime.principal_id
}

resource "azurerm_key_vault_secret" "ai_search_endpoint" {
  name         = "azure-ai-search-endpoint"
  value        = "https://${azurerm_search_service.library.name}.search.windows.net"
  key_vault_id = azurerm_key_vault.cron_obs.id
  content_type = "text/url"

  tags = {
    "ai-feature"  = "search"
    "secret-kind" = "endpoint-url"
  }

  depends_on = [azurerm_role_assignment.kv_secrets_officer_terraform_runner]
}

# ─── Anomaly Detector → Slack alert wiring ──────────────────────────────────
#
# The Anomaly Detector account itself does not push alerts — the
# cron job (`services/backend/azure_ai/anomaly_detector.py`) polls
# the time-series endpoints and emits a `ai_anomaly_detected` custom
# metric to App Insights. The metric alert below converts that into
# a Slack ping via the existing `ops_alerts` action group from
# `observability.tf`. No new action group is created; reuse keeps
# the Slack rotation marker single-sourced.

resource "azurerm_monitor_metric_alert" "ai_anomaly_detected" {
  name                = "${local.lz_project}-ai-anomaly-detected"
  resource_group_name = azurerm_resource_group.cron_obs.name
  scopes              = [azurerm_application_insights.cron_obs.id]
  description         = "Azure Anomaly Detector flagged a credit-burn / error-rate / R2-cost outlier."
  severity            = 2 # warning — runbook step is to inspect the offending series, not auto-remediate
  frequency           = "PT5M"
  window_size         = "PT15M"
  enabled             = true

  criteria {
    metric_namespace = "Azure.ApplicationInsights"
    metric_name      = "customMetrics/ai_anomaly_detected"
    aggregation      = "Total"
    operator         = "GreaterThan"
    threshold        = 0
  }

  action {
    action_group_id = azurerm_monitor_action_group.ops_alerts.id
  }

  tags = merge(local.lz_common_tags, {
    "ai-feature" = "anomaly_detector"
  })
}

# ─── Outputs ────────────────────────────────────────────────────────────────

output "azure_ai_endpoints" {
  description = "Map of feature name → Cognitive Services endpoint URL. Consumed by services/backend/azure_ai/_resolver.py via Key Vault."
  value       = { for k, acc in azurerm_cognitive_account.ai : k => acc.endpoint }
}

output "azure_ai_search_endpoint" {
  description = "AI Search endpoint URL. Consumed by services/backend/azure_ai/search.py."
  value       = "https://${azurerm_search_service.library.name}.search.windows.net"
}

output "azure_ai_account_principals" {
  description = "Map of feature → system-assigned identity principal ID. Used when an AI service needs to read S3 via OIDC trust on the AWS side (Document Intelligence presigned-URL ingest)."
  value       = { for k, acc in azurerm_cognitive_account.ai : k => acc.identity[0].principal_id }
}
