"""vertex_format — Vertex / Gemini 2.5 Flash content-formatter ONLY.

Task #490 — Vertex is no longer a chat hot-path provider, multilingual
embedder, or Vector Search backend. The single remaining role is
NotebookLM-style polish/format of already-generated content (V4 §15
amendment). All other Vertex call-sites (chat dispatch, vision,
translate, embed, vector_search) have been deleted.

Public API:

    await format_with_vertex(text, *, style="notebook_lm", lang="en",
                             max_tokens=4000, timeout_s=15.0) -> str

`style` selects the system prompt template ("notebook_lm" is the only
shipped style today; future styles can be appended without callers
having to change). `lang` controls language preservation ("en" or
"as"); the formatter is forbidden from translating between languages.

Auth: GOOGLE_APPLICATION_CREDENTIALS_JSON service account JSON blob,
project picked from GCP_PROJECT_ID / GOOGLE_CLOUD_PROJECT /
VERTEX_PROJECT_ID / SA `project_id`. Region from VERTEX_LOCATION
(default us-central1). Model from VERTEX_GEMINI_MODEL
(default gemini-2.5-flash).

Failure mode: raises RuntimeError on misconfiguration, httpx.HTTPError
on transport, RuntimeError on empty/blocked Vertex response. Callers
own the fall-through (V4 §12 — no silent fallbacks).
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
import re
from typing import Optional

logger = logging.getLogger(__name__)

# Re-exported circuit breaker from the legacy vertex_chat module so any
# admin/health code that imported `vertex_chat.breaker_snapshot()` keeps
# working through the rename.
from vertex_breaker import CircuitBreaker

_BREAKER_THRESHOLD = max(1, int(os.environ.get("VERTEX_FORMAT_BREAKER_THRESHOLD", "3")))
_BREAKER_COOLDOWN_S = max(1.0, float(os.environ.get("VERTEX_FORMAT_BREAKER_COOLDOWN_S", "180")))
_breaker = CircuitBreaker(
    name="vertex_format",
    failure_threshold=_BREAKER_THRESHOLD,
    cooldown_s=_BREAKER_COOLDOWN_S,
)

_VERTEX_CACHE: dict = {}

# ── system prompts ──────────────────────────────────────────────────────────
_NOTEBOOK_LM_SYSTEM_EN = (
    "You are a senior academic editor producing NotebookLM-style study notes. "
    "Polish the user's raw notes into clean Markdown: ## for topic headings, "
    "### for sub-points, **bold** for every key term and definition on first "
    "mention, 4-6 tightened bullets per topic, no redundancy, no filler. "
    "Preserve the original topic structure exactly — do NOT add new topics, "
    "do NOT drop topics. End with one final '## Key Takeaways' section "
    "containing 5-7 exam-critical bullets. Return ONLY the polished Markdown "
    "— no commentary, no preamble, no disclaimers."
)
_NOTEBOOK_LM_SYSTEM_AS = (
    "You are an Assamese-fluent academic editor producing NotebookLM-style "
    "study notes. The user's raw notes are in Assamese (অসমীয়া) and may be "
    "rough — generated by an Indic translation model. Output MUST stay in "
    "Assamese script throughout — do NOT translate to English. Polish into "
    "clean Markdown: ## for topic headings, ### for sub-points, **bold** for "
    "every key term and definition on first mention, 4-6 tightened bullets "
    "per topic, no redundancy. Preserve the original topic structure exactly. "
    "End with '## মূল কথাবোৰ' (Key Takeaways) containing 5-7 exam-critical "
    "bullets. Return ONLY the polished Markdown — no English commentary, no "
    "preamble, no disclaimers."
)


def _select_system_prompt(style: str, lang: str) -> str:
    style_norm = (style or "notebook_lm").strip().lower()
    lang_norm = (lang or "en").strip().lower()
    if style_norm != "notebook_lm":
        raise ValueError(
            f"vertex_format: unknown style {style!r} — only 'notebook_lm' "
            f"is shipped today"
        )
    return _NOTEBOOK_LM_SYSTEM_AS if lang_norm.startswith("as") else _NOTEBOOK_LM_SYSTEM_EN


def is_configured() -> bool:
    """True iff the service account JSON blob is present in env."""
    return bool((os.environ.get("GOOGLE_APPLICATION_CREDENTIALS_JSON", "") or "").strip())


def is_available() -> bool:
    return is_configured() and _breaker.allow()


def auth_mode() -> str:
    return "vertex_sa" if is_configured() else "unconfigured"


def breaker_snapshot() -> dict:
    return _breaker.snapshot()


def force_breaker_close() -> None:
    _breaker.force_close()


async def _ensure_creds():
    """Lazy-load + refresh the SA credentials. Cached process-wide."""
    from google.oauth2 import service_account
    from google.auth.transport.requests import Request as _GAuthReq

    if "creds" not in _VERTEX_CACHE:
        sa_raw = (os.environ.get("GOOGLE_APPLICATION_CREDENTIALS_JSON", "") or "").strip()
        if not sa_raw:
            raise RuntimeError("vertex_format: GOOGLE_APPLICATION_CREDENTIALS_JSON not set")
        sa_info = json.loads(sa_raw)
        creds = service_account.Credentials.from_service_account_info(
            sa_info, scopes=["https://www.googleapis.com/auth/cloud-platform"],
        )
        _VERTEX_CACHE["creds"] = creds
        _VERTEX_CACHE["project"] = (
            os.environ.get("GCP_PROJECT_ID")
            or os.environ.get("GOOGLE_CLOUD_PROJECT")
            or os.environ.get("VERTEX_PROJECT_ID")
            or sa_info.get("project_id")
        )
    creds = _VERTEX_CACHE["creds"]
    if not creds.valid:
        await asyncio.to_thread(creds.refresh, _GAuthReq())
    project = _VERTEX_CACHE["project"]
    if not project:
        raise RuntimeError("vertex_format: project_id missing from SA JSON / env")
    return creds, project


async def format_with_vertex(
    text: str,
    *,
    style: str = "notebook_lm",
    lang: str = "en",
    max_tokens: int = 4000,
    timeout_s: float = 15.0,
) -> str:
    """Polish/format ``text`` via Vertex AI Gemini 2.5 Flash.

    Returns the polished Markdown string. Raises on misconfiguration,
    HTTP failure, breaker-open, or empty / safety-blocked Vertex
    response. Callers MUST handle the failure path themselves — there
    is no silent fallback (V4 §12 / §15).
    """
    if not text or not text.strip():
        raise ValueError("vertex_format: empty input text")
    if not _breaker.allow():
        raise RuntimeError("vertex_format: circuit breaker open — refusing call")

    system_prompt = _select_system_prompt(style, lang)
    creds, project = await _ensure_creds()

    location = (os.environ.get("VERTEX_LOCATION", "us-central1") or "us-central1").strip()
    model = (os.environ.get("VERTEX_GEMINI_MODEL", "gemini-2.5-flash") or "gemini-2.5-flash").strip()
    url = (
        f"https://{location}-aiplatform.googleapis.com/v1/projects/{project}"
        f"/locations/{location}/publishers/google/models/{model}:generateContent"
    )
    payload = {
        "contents": [{"role": "user", "parts": [{"text": text}]}],
        "systemInstruction": {"parts": [{"text": system_prompt}]},
        "generationConfig": {"maxOutputTokens": max_tokens, "temperature": 0.1},
    }

    import httpx as _httpx
    try:
        async with _httpx.AsyncClient(timeout=timeout_s) as c:
            r = await c.post(
                url,
                headers={
                    "Authorization": f"Bearer {creds.token}",
                    "Content-Type": "application/json",
                },
                json=payload,
            )
        r.raise_for_status()
    except Exception as exc:
        _breaker.record_failure(type(exc).__name__)
        raise

    data = r.json()
    parts = (data.get("candidates") or [{}])[0].get("content", {}).get("parts") or []
    out = "".join(p.get("text", "") for p in parts).strip()
    out = re.sub(r"<think>.*?</think>", "", out, flags=re.DOTALL).strip()
    if not out:
        _breaker.record_failure("empty_response")
        raise RuntimeError("vertex_format: Vertex returned empty / blocked response")
    _breaker.record_success()
    return out
